name: X, X Everywhere
source: https://knowyourmeme.com/memes/x-x-everywhere
keywords:
  - buzz
  - woody
  - toy story
  - everywhere
  - trouble
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - memes
  - memes everywhere
overlay:
  - center_x: 0.85
    center_y: 0.3
    angle: 0.0
    scale: 0.25
