name: Goblin Pacha
source: 
  https://knowyourmeme.com/memes/pacha-edits-when-the-sun-hits-that-ridge-just-right
keywords:
  - pacha
  - emperors new groove
  - perfection
  - just right
  - ok hand
  - goblin
  - green skin
  - fantasy
text:
  - style: UPPER
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 0.0
  - style: LOWER
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 0.0
example:
  - when the loot
  - is just right
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
