name: Distracted Boyfriend
source: https://knowyourmeme.com/memes/distracted-boyfriend
keywords:
  -
text:
  - style: default
    color: white
    font: thick
    anchor_x: 0.10
    anchor_y: 0.68
    angle: 0.0
    scale_x: 0.295
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thick
    anchor_x: 0.51
    anchor_y: 0.44
    angle: 0.0
    scale_x: 0.275
    scale_y: 0.1
    align: center
    start: 0.0
    stop: 1.0
  - style: default
    color: white
    font: thick
    anchor_x: 0.67
    anchor_y: 0.63
    angle: 0.0
    scale_x: 0.3
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - Art DeCC0s
  - You
  - Your Paper Doll PFPs
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25