name: Decc0 Hotline
source:
keywords:
  - decc0
  - drake
  - hotline
  - yes
  - no
text:
  - style: upper
    color: black
    font: thick
    anchor_x: 0.5
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.5
    align: center
    start: 0.0
    stop: 1.0
  - style: upper
    color: black
    font: thick
    anchor_x: 0.5
    anchor_y: 0.5
    angle: 0.0
    scale_x: 0.5
    scale_y: 0.5
    align: center
    start: 0.0
    stop: 1.0
example:
  - using the old meme
  - using the Decc0 meme
overlay:
  - center_x: 0.25
    center_y: 0.25
    angle: 0.0
    scale: 0.25
  - center_x: 0.25
    center_y: 0.75
    angle: 0.0
    scale: 0.25
