name: Evil Gatsby
source: http://knowyourmeme.com/memes/leonardo-dicaprio-cheers
keywords:
  - gatsby
  - toast
  - leonardo dicaprio
  - evil
  - red eyes
  - sinister
  - cursed
  - celebration
text:
  - style: UPPER
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 0.0
  - style: LOWER
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.8
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 0.0
example:
  - when the chaos
  - goes exactly as planned
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
