name: Alien Ape
source: https://knowyourmeme.com/memes/alien-ape
keywords:
  - alien
  - ape
  - portrait
  - duo
  - mysterious
text:
  - style: UPPER
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.0
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
  - style: UPPER
    color: white
    font: thick
    anchor_x: 0.0
    anchor_y: 0.8
    angle: 0.0
    scale_x: 1.0
    scale_y: 0.2
    align: center
    start: 0.0
    stop: 1.0
example:
  - me explaining to my friend
  - why aliens built the pyramids
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
