name: Artistic Success Kid
source: https://knowyourmeme.com/memes/success-kid
keywords:
  - success kid
  - baby
  - art
  - painting
  - surreal
  - victory
  - fist
text:
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.0
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.25
    align: center
    start: 0.0
    stop: 0.0
  - style: upper
    color: white
    font: thick
    anchor_x: 0.05
    anchor_y: 0.75
    angle: 0.0
    scale_x: 0.9
    scale_y: 0.25
    align: center
    start: 0.0
    stop: 0.0
example:
  - painted a masterpiece
  - finger painting
overlay:
  - center_x: 0.5
    center_y: 0.5
    angle: 0.0
    scale: 0.25
